adoptopenjdk14:
  version: 14.0.1.j9-adpt

adoptopenjdk13:
  version: 13.0.2.j9-adpt

docker_compose:
  version: 1.25.5

jetbrains_toolbox:
  version: 1.16.6319

micronaut:
  version: 1.3.5

visual_studio_code:
  config: https://gist.githubusercontent.com/xalvarez/f6abc34fb56f766820db3a3cb1287a4a/raw/settings.json
