---
- import_tasks: snap.yml
- import_tasks: flatpak.yml

- import_tasks: jetbrains_toolbox.yml
  become: no

- import_tasks: docker.yml
- import_tasks: nodejs.yml

- import_tasks: bash_git_prompt.yml
  become: no