---
- import_tasks: apt.yml

- import_tasks: sdkman.yml
  become: no

- import_tasks: snap.yml
  async: 600
  poll: 0

- name: Check if Jetbrains Toolbox is already installed
  stat:
    path: ~/.local/bin/jetbrains-toolbox
  register: toolbox
  become: no

- import_tasks: jetbrains_toolbox.yml
  become: no
  when: not toolbox.stat.exists

- import_tasks: nodejs.yml

- import_tasks: bash_git_prompt.yml
  become: no

- import_tasks: docker.yml
