- name: Add Node.js GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add Node.js apt repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_10.x bionic main

- name: Install Node.js
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
  vars:
    packages:
    - nodejs
    - gcc
    - g++
    - make