---
- name: Check if SDKMAN! is already installed
  stat:
    path: ~/.sdkman
  register: sdkman

- name: Download SDKMAN! installation script
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/install_sdkman.sh
    mode: u+x
  register: download
  when: not sdkman.stat.exists

- name: Install SDKMAN!
  command: /tmp/install_sdkman.sh
  when: not sdkman.stat.exists

- name: Install SDKMAN! applications
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item.name }} {{ item.version }}
  args:
    executable: /bin/bash
  register: installation
  failed_when:
    - installation.rc != 0
    - '"is already installed" not in installation.stdout'
  changed_when: installation.rc == 0
  loop:
    - { name: 'java', version: '{{ adoptopenjdk14.version }}'}
    - { name: 'java', version: '{{ adoptopenjdk13.version }}'}
    - { name: 'java', version: '{{ adoptopenjdk11.version }}'}

- name: Set up default JDK to {{ adoptopenjdk11.version }}
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk default java {{ adoptopenjdk11.version }}
  args:
    executable: /bin/bash
  register: default
  changed_when: default.rc == 0
